spring:
  application:
    name: mic-product-service


  data:
    mongodb:
      uri: mongodb://localhost
      database: product

  kafka:
    topic: event.product.changed
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      properties:
        retries: 100
        retry.backoff.ms: 1000
        '[schema.registry.url]': http://localhost:8081

    consumer:
      group-id: "group-1"
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        '[schema.registry.url]': http://localhost:8081
        '[specific.avro.reader]': true