spring:
  application:
    name: mic-product-service


  data:
    mongodb:
      uri: mongodb://localhost
      database: product
      auto-index-creation: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      properties:
        retries: 100
        retry.backoff.ms: 1000
        '[schema.registry.url]': http://localhost:8081

    consumer:
      group-id: "group-1"
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        '[schema.registry.url]': http://localhost:8081
        '[specific.avro.reader]': true
app:
  api:
    base-url: /api/v1
  bindings:
    topics:
      '[com.banreservas.product.avro.v1.ProductCreatedEventV1]': product-created-v1
      '[com.banreservas.product.avro.v1.ProductUpdatedEventV1]': product-updated-v1
      '[com.banreservas.product.avro.v1.ProductDeletedEventV1]': product-deleted-v1
  service:
    default-currency: DOP

external:
  exchange-rate-api:
    key: 9120c6a502716521e8984bd8
    base-url: https://v6.exchangerate-api.com